keys:
  styles:
    default:  # Rough approximation of MT3 family.
      style: maquette
      switch-type: mx
      top-size: [12.75, 12.75, 6.7]
      skirt-thickness: 3.6
      skirt-length: 4.0
    r1:
      style: maquette
      switch-type: mx
      top-size: [12.75, 12.75, 9.5]
      skirt-thickness: 3.6
      skirt-length: 4.0
    r2:
      style: maquette
      switch-type: mx
      top-size: [12.75, 12.75, 7.2]
      skirt-thickness: 3.6
      skirt-length: 4.0
    r3:
      style: maquette
      switch-type: mx
      top-size: [12.75, 12.75, 6.7]
      skirt-thickness: 3.6
      skirt-length: 4.0
    r4:
      style: maquette
      switch-type: mx
      top-size: [12.75, 12.75, 7.2]
      skirt-thickness: 3.6
      skirt-length: 4.0
    r5:
      style: maquette
      switch-type: mx
      top-size: [12.75, 12.75, 9.5]
      skirt-thickness: 3.6
      skirt-length: 4.0
    r1w:
      style: maquette
      switch-type: mx
      top-size: [22.75, 12.75, 9.5]
      skirt-thickness: 3.6
      skirt-length: 4.0
      unit-size: [1.5, 1]
    r2w:
      style: maquette
      switch-type: mx
      top-size: [22.75, 12.75, 7.2]
      skirt-thickness: 3.6
      skirt-length: 4.0
      unit-size: [1.5, 1]
    r3w:
      style: maquette
      switch-type: mx
      top-size: [22.75, 12.75, 6.7]
      skirt-thickness: 3.6
      skirt-length: 4.0
      unit-size: [1.5, 1]
    r4w:
      style: maquette
      switch-type: mx
      top-size: [22.75, 12.75, 7.2]
      skirt-thickness: 3.6
      skirt-length: 4.0
      unit-size: [1.5, 1]
    r5w:
      style: maquette
      switch-type: mx
      top-size: [22.75, 12.75, 9.5]
      skirt-thickness: 3.6
      skirt-length: 4.0
      unit-size: [1.5, 1]
    r3t:
      style: maquette
      switch-type: mx
      top-size: [12.75, 22.75, 6.7]
      skirt-thickness: 3.6
      skirt-length: 4.0
      unit-size: [1, 1.5]